### ISSUE TITLE
this line could be simplified a bit

### ISSUE THREAD

**Issue by jwld** [FACN1/week6-D-REEM-TEAM#42]
https://github.com/FACN1/week6-D-REEM-TEAM/blob/master/src/routes/staticFile.js#L8

Why not just say `if (req.url === '/')`?

**Comment by macintoshhelper** [comment]
This line means that directory URLs such as `/fruit/apple` will load the html page `/fruit/apple/index.html`

**Comment by jwld** [comment]
ahhh nice
