### ISSUE TITLE
why use res.write()?

### ISSUE THREAD

**Issue by jwld** [FACN1/week6-D-REEM-TEAM#44]
https://github.com/FACN1/week6-D-REEM-TEAM/blob/master/src/routes/staticFile.js#L35-L36

Could you not just say `res.end(file)`?

**Comment by macintoshhelper** [comment]
res.write can be used multiple times, e.g.:  res.write(headerHtml), res.write(bodyHtml). It's used for consistency to not have res.write in some areas and res.end in some areas.

**Comment by jwld** [comment]
kewl
